import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import '@/styles/globals.css';
import { Header } from '@/components/ui/header';
import { AppProvider } from '@/providers/app';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ! https://github.com/shadcn/next-contentlayer/issues/7
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AppProvider>
          <main className="flex min-h-screen flex-col">
            <Header />
            {children}
          </main>
        </AppProvider>
      </body>
    </html>
  );
}
